[[main]]
none = "none"

[[main]]
name = "Aktuelles"
pageRef = "aktuelles"
identifier = "jy3g4yauvU"
weight = 9998

[[main]]
name = "Einsätze"
pageRef = "einsätze"
identifier = "UGhZYTK6Jw"
weight = 9998

[[main]]
name = "Über uns"
pageRef = "über-uns"
identifier = "A3kRTnMzG9"
weight = 9999

[[main]]
name = "Downloads"
pageRef = "downloads"
identifier = "TrST8QabLX"
weight = 9999

[[footer]]
none = "none"

[[footer]]
name = "Instagram"
url = "https://instagram.com/feuerwehr.liekwegen"
identifier = "B2wvgay90r"
weight = 9999

[[footer]]
name = "Facebook"
url = "https://www.facebook.com/feuerwehrliekwegen/"
identifier = "AaIUDA9asu"
weight = 999
